### ISSUE TITLE
module use --help / -h unexpected behavior

### ISSUE THREAD

**Issue by pavelToman** [TACC/Lmod#697] opened 2024-03-13 09:53 UTC
There is a problem with command `module use -h` and `module use --help`. It adds `~/-h` or `~/--help` to $MODULEPATH instead of showing the help.
`ml use -h` and `ml use --help` works correctly.

Operating System: Red Hat Enterprise Linux 8.8 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-477.43.1.el8_8.x86_64
Architecture: x86-64
Lmod Version: Modules based on Lua: Version 8.7.4

**Comment by rtmclay** [comment] 2024-03-13 12:43
This not a bug.  All options come before a command.  So::

```
% module --help use
```

is correct.

where as:
```
% module use --help
```
adds  ~/--help  to $MODULEPATH

**Comment by boegel** [comment] 2024-03-13 20:45
@rtmclay It is a bit counterintuitive though (I asked @pavelToman to report this directly when he mentioned it to me)

**Comment by rtmclay** [comment] 2024-03-14 17:03
What I said before is still true.  All options must be specified before the command:
```
% module <option(s)> command
% ml         <options> command
```
So this means that
```
% module use --help
```
will add $PWD/--help to $MODULEPATH

However 
```
% ml use --help
```
should to the same thing as ```module use --help```.  I have modified the testing branch so that both commands now do the same thing.

Please try the testing branch out to see that it works for you.

**Comment by rtmclay** [comment] 2024-03-15 01:47
This change has now been merged into the main branch and has been released as Lmod 8.7.36.

**Comment by boegel** [comment] 2024-04-02 14:47
@rtmclay As discussed during today's Lmod monthly call, maybe a warning could be printed when the use of `--help` looks "fishy", something like:

```
$ module use --help
Warning: adding '--help' to $MODULEPATH, maybe you intended to use `module --help use`?
```

**Comment by rtmclay** [comment] 2024-06-02 18:04
See the release of Lmod 8.7.39 to see if this solves your problem.

**Comment by rtmclay** [comment] 2024-06-17 17:55
I'm closing this issue.  Feel free to re-open this issue if necessary.

**Closed by rtmclay** 2024-06-17 17:55 UTC
