### ISSUE TITLE
${LMODPATH}/etc/rc does not work anymore with lmod 8.0

### ISSUE THREAD

**Issue by clsgithubusr** [TACC/Lmod#401] opened 2019-03-28 09:03 UTC
Hi
I have upgraded Lmod to version 8.0, but now the system-wide rc cannot be parsed anymore:

`
Lmod has detected the following error:  Unable to parse: "${LMOD_LIBEXEC_PATH}/../../etc/rc".
Aborting!
`

**Comment by rtmclay** [comment] 2019-03-28 15:58
I have tested Lmod and my test shows that it reads at least one RC file.  So there must be something specific about your setup.  What version of Lmod were you running previously? Could you make a small reproducer?  You can start with sending me your RC file.

**Comment by clsgithubusr** [comment] 2019-03-29 08:08
- previous version: 7.8.11

Part of the rc file:
```sh
#%Module
hide-version 80merslidingwindow/1-foss-2016b
hide-version ABySS/1.9.0-foss-2016a
hide-version AlignQC/2.0.5-foss-2018b-Python-2.7.15
hide-version AMOS/3.1.0-foss-2016b
hide-version Anaconda2/4.2.0
hide-version Anaconda2/4.4.0
hide-version ant/1.10.1-Java-1.8.0_144
hide-version ant/1.10.1-Java-1.8.0_144
hide-version ant/1.10.5-Java-1.8
hide-version ant/1.9.7-Java-1.8.0_92
hide-version ant/1.9.7-Java-1.8.0_92
hide-version ...
```

It only contains hidden versions.

**Comment by rtmclay** [comment] 2019-03-29 15:05
Thanks for letting me see your RC file.  I added some hide-version statements to my RC file in my test and it works correctly.  It looks like I am going to need a reproducer to see what is going on.  Please send via email me the output of "module --config" and "module -D load _something_ 2> load.log" or something that causes the error.

**Comment by rtmclay** [comment] 2019-04-01 13:20
I can reproduce the problem on a system running Centos 6.8.  On what system are you finding the problem?  Also what version of TCL are you using?

 ```
$ echo 'puts [info patchlevel]' | tclsh
```

**Comment by clsgithubusr** [comment] 2019-04-01 15:20
Hi Robert
```
$  echo 'puts [info patchlevel]' | tclsh
8.5.13

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

I will send the output of "module --config" to your mail.

**Comment by clsgithubusr** [comment] 2019-04-01 15:29
I am not getting this issue on a RHEL7.5 system.

```
 $ echo 'puts [info patchlevel]' | tclsh
8.5.13
 $ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
 $ module --version
Modules based on Lua: Version 8.0  2019-03-26 17:00 -05:00
    by Robert McLay mclay@tacc.utexas.edu

```

**Comment by rtmclay** [comment] 2019-04-05 00:52
I found the problem with the c code (pkgs/tcl2lua/tcl2lua.c) where in some version of the tcl interpreter would not keep the result value around.  This is fixed by copying the result string into an internal buffer. This fixes the problem for me.  Please test Lmod 8.0.1 to see if it fixes it for you.

**Comment by clsgithubusr** [comment] 2019-04-08 08:43
Hi Robert

It is not fixed for me 
````sh
$ module --version

Modules based on Lua: Version 8.0.1  2019-04-04 19:32 -05:00
    by Robert McLay mclay@tacc.utexas.edu

$ module avail
Lmod has detected the following error:  Unable to parse: "/usr/share/lmod/lmod/libexec/../../etc/rc". Aborting!

```

**Comment by rtmclay** [comment] 2019-04-08 15:27
I have a few things to try.   What happens if you do:

```
$ cd src; ./RC2lua.tcl ../rt/end2end/modulerc
```
I get:
```
ModA={
{kind="module_version",module_name="amber/1.1", module_versionA={"default"}},
{kind="hide_version", mfile="amber/0.9"},
{kind="hide_version", mfile="amber/1.0"},
}
```

Now try running without the fast TCL interpreter:
```
 $ LMOD_FAST_TCL_INTERP=no module avail
```

What happens if you do the following in the source tree:

```
$ cd embed; gcc -o tryMe tcl_my_prt.c -ltcl
$  ./tryMe ../src/RC2lua.tcl -F ../rt/end2end/modulerc 
```

Please let me know what you find so we can track down what the problem is.

**Comment by clsgithubusr** [comment] 2019-04-08 15:34
Hi Robert

```sh
src $ ./RC2lua.tcl ../rt/end2end/modulerc
ModA={
{kind="module_version",module_name="amber/1.1", module_versionA={"default"}},
{kind="hide_version", mfile="amber/0.9"},
{kind="hide_version", mfile="amber/1.0"},
}

```

```sh
src $ LMOD_FAST_TCL_INTERP=no module avail
couldn't read file "/usr/share/lmod/lmod/libexec/../../etc/rc": no such file or directory
    while executing
"source $mRcFile"
    (procedure "main" line 9)
    invoked from within
"main $fn"
    (file "/usr/share/lmod/lmod/libexec/RC2lua.tcl" line 131)
Lmod has detected the following error:  Unable to parse: "/usr/share/lmod/lmod/libexec/../../etc/rc". Aborting!
```

```sh
embed $ ./tryMe ../src/RC2lua.tcl -F ../rt/end2end/modulerc 
len: 170, resultStr: "ModA={
{kind="module_version",module_name="amber/1.1", module_versionA={"default"}},
{kind="hide_version", mfile="amber/0.9"},
{kind="hide_version", mfile="amber/1.0"},
}"

```

**Comment by rtmclay** [comment] 2019-04-08 15:45
So does the file ```/usr/share/lmod/lmod/libexec/../../etc/rc``` exist but is not readable by you?

**Comment by clsgithubusr** [comment] 2019-04-10 11:16
Yes I have access to read it
$ ls -la /usr/share/lmod/lmod/libexec/../../etc/rc
-rw-r--r-- 1 root root 47805 Mar 28 09:58 /usr/share/lmod/lmod/libexec/../../etc/rc

**Comment by rtmclay** [comment] 2019-04-10 15:00
I have just release Lmod 8.0.3.  It has some fixes that may help with your issue.  I do have some questions.  As I understand it, Lmod fails to work on a RHEL 7.6 system.  Is the Lmod install on that system just for that system or is Lmod built on a different system and installed there? Or is there a common area where different systems share?

Please test Lmod 8.0.3 with the following test on the system that failed:

```
$ LMOD_FAST_TCL_INTERP=no module avail
```
and 
```
$ module avail
```

Also try 

```
$ LMOD_MODULERCFILE=<lmod_source_tree>/rc/end2end/modulerc module avail
```

where you have replaced <lmod_source_tree> with the location of the lmod source.

If the either of the first two steps fail.  Please send me your rc file so that I can try and reproduce the problem.

**Comment by clsgithubusr** [comment] 2019-04-11 09:35
Hi Robert

After compiling the latest version of Lmod(./configure --prefix=/usr/share/
, make install), everything is working.

But then I am making an rpm of it, I upload it to our internal repo server, and when I upgrade Lmod with (yum upgrade Lmod) It is not working anymore on the same server where I have compiled Lmod( and other servers)

```sh
$ cd <lmod_source_tree>
$ ./configure --prefix=/usr/share/
$ make install
$ module --version
Modules based on Lua: Version 8.0.3  2019-04-10 09:45 -05:00
    by Robert McLay mclay@tacc.utexas.edu

$ LMOD_FAST_TCL_INTERP=no module avail #is working
$ module avail #is working

```

then I install Lmod with the rpm package(it is failing on other systems as well)

```sh
$ sudo yum upgrade Lmod
$ module --version

Modules based on Lua: Version 8.0.3  2019-04-10 09:45 -05:00
    by Robert McLay mclay@tacc.utexas.edu
$  LMOD_FAST_TCL_INTERP=no module avail 
couldn't read file "/usr/share/lmod/lmod/libexec/../../etc/rc": no such file or directory
    while executing
"source $mRcFile"
    (procedure "main" line 9)
    invoked from within
"main $fn"
    (file "/usr/share/lmod/lmod/libexec/RC2lua.tcl" line 131)
Lmod has detected the following error:  Unable to parse: "/usr/share/lmod/lmod/libexec/../../etc/rc". Aborting!

$ module avail
couldn't read file "/usr/share/lmod/lmod/libexec/../../etc/rc": no such file or directory
    while executing
"source $mRcFile"
    (procedure "main" line 9)
    invoked from within
"main $fn"
    (file "/usr/share/lmod/lmod/libexec/RC2lua.tcl" line 131)
Lmod has detected the following error:  Unable to parse: "/usr/share/lmod/lmod/libexec/../../etc/rc". Aborting!

$ LMOD_MODULERCFILE=Lmod/rt/end2end/modulerc module avail #is working
```

**Comment by rtmclay** [comment] 2019-04-11 17:44
It looks like there is a problem with the rpm spec file and not Lmod itself.  Has the Lmod spec file updated for 8.0+.  Namely is there a lib directory in the installed rpm? Does the new spec file know about the updated tcl -devel requirements?

What happens if you install the rpm and then replace the lib directory contents with the configure; make install version?

**Comment by rtmclay** [comment] 2019-04-11 18:06
One other idea I have is to make sure that all the files that where in the ./configure; make install version are in the installed files from the rpm.

**Comment by clsgithubusr** [comment] 2019-04-12 09:30
Hi Robert

I finally found out why.
When i received this error, I just copied the /usr/share/lmod/8.0.3 directory to my rpm build location. and I have created a symlink manually in of /usr/share/lmod/8.0.3 to /usr/share/lmod/lmod in my build location.

But it seems I needed to copy the whole directory /usr/share/lmod to my rpm build location. I didn't know there  were any differences.

**Comment by rtmclay** [comment] 2019-04-15 16:27
There are some rules that Lmod follows when deciding where to put files. Obviously if one installing Lmod in /usr/share then the directory structure is as follows:
```
$ cd /usr/share/lmod
$ tree -L 1
.
├── 8.0.3
├── etc
└── lmod -> 8.0.3

It is assumed that the etc directory would not be part of an rpm or similar package system.  Instead the files in the etc directory independent of a particular Lmod version install.  The files that go into etc/ are the rc file and the admin.list file (aka the nag file).  These files probably do not depend on the version of Lmod so that is why they are not normally part of an rpm package file.

If you want to make them part of an Lmod install you can move them down to a directory and set the appropriate env. vars:

LMOD_MODULERCFILE 
LMOD_ADMIN_FILE

**Comment by rtmclay** [comment] 2019-04-18 22:07
Ok to close this issue?

**Comment by clsgithubusr** [comment] 2019-04-19 11:27
Yes Robert, the ticket can be closed.

Thank you for all your feedback and help. I really appreciate it .

**Comment by moskalenko** [comment] 2019-06-27 20:45
I'm running into something similar to this when testing an upgrade for Lmod 7.8.19 to 8.1.7 but the issue seems to be stemming from the path and not from the rc file contents

$ ml ufrc
couldn't read file "/apps/lmod/dev/libexec/../../etc/rc": no such file or directory
    while executing
"source $mRcFile"
    (procedure "main" line 9)
    invoked from within
"main $fn"
    (file "/apps/lmod/dev/libexec/RC2lua.tcl" line 131)
Lmod has detected the following error:  Unable to parse: "/apps/lmod/dev/libexec/../../etc/rc". Aborting!

$ ls -al /apps/lmod/dev/libexec/../../etc/rc
-rw-rw-r-- 1 moskalenko ufhpc 1902 Jun 27 16:38 /apps/lmod/dev/libexec/../../etc/rc

The issue is not with the rc file, but path handling in Tcl itself it seems since this works:

$ LMOD_MODULERCFILE=/apps/lmod/etc/rc ml ufrc

But the following doesn't work even though the shell can expand this path just fine

$ LMOD_MODULERCFILE=/apps/lmod/dev/libexec/../../etc/rc ml ufrc
couldn't read file "/apps/lmod/dev/libexec/../../etc/rc": no such file or directory

$ ls -al /apps/lmod/dev/libexec/../../etc/rc
-rw-rw-r-- 1 moskalenko ufhpc 1902 Jun 27 16:38 /apps/lmod/dev/libexec/../../etc/rc

**Comment by moskalenko** [comment] 2019-06-27 20:47
This is on RHEL-7.5 by the way.

**Comment by rtmclay** [comment] 2019-06-27 21:00
What does:

$ ml --config 

say?

**Comment by moskalenko** [comment] 2019-06-27 21:08
I went one step further and used

So, ml -config now has

MODULERCFILE                       /apps/lmod/etc/rc
Admin file                         /apps/lmod/dev/libexec/../../etc/admin.list

and

Changes from Default Configuration
----------------------------------

Name                   Default  Value
----                   -------  -----
LFS_VERSION            1.6.3    1.6.2
LMOD_ALLOW_TCL_MFILES  yes      no
LMOD_FAST_TCL_INTERP   no       yes
LMOD_LD_LIBRARY_PATH   false    /opt/slurm/lib64::
LMOD_PAGER             less     less -XqMREF
LMOD_REDIRECT          no       yes
LMOD_SITE_NAME         false    UFRC
LMOD_TCLSH             tclsh    /usr/bin/tclsh
MODULEPATH_ROOT                 /apps/lmod/devmodulefiles
PATH_TO_LUA            lua      /usr/bin

That didn't help.

When I patched myGlobals.lua as a test the issue went away:

$ diff myGlobals.lua.orig myGlobals.lua
297c297
<    rc_dflt   = pathJoin(cmdDir(),"../../etc/rc")
---
>    rc_dflt   = "/apps/lmod/etc/rc"

**Comment by rtmclay** [comment] 2019-07-01 20:24
I have changed Lmod to use the LMOD_PKG env. var. if set instead of using: ```rc_dflt   = pathJoin(cmdDir(),"../../etc/rc")```

Please see if version 8.1.8 fixes this problem for you.

**Comment by rtmclay** [comment] 2019-07-01 20:39
After checking 8.1.8 myself, I see that it is incorrect.  Please wait until 8.1.9 before testing.

**Comment by rtmclay** [comment] 2019-07-01 21:24
Please test Lmod 8.1.9 to see if new version works for you.  Thanks!

**Comment by moskalenko** [comment] 2019-07-02 20:12
Thanks for taking a look Robert!

I installed and tested Lmod-8.1.9. From the patch it looks like the solution is to set LMOD_ROOT and use it to build the path to sysconfdir. That works just as setting MODULERCFILE explicitly solves the issue, same as with 8.1.7. Unfortunately,  '--sysconfdir=/apps/lmod/devetc' used with './configure' is still ignored. It would be great if that were an alternative solution to avoid having to patch /etc/profile.d/modules.sh cluster-wide.

$ ml --config 2>&1 | grep MODULERC
MODULERCFILE                       /apps/lmod/dev/libexec/../../etc/rc

If setting LMOD_ROOT or MODULERCFILE is the only viable approach to resolving the issue I'll go ahead and ask our systems people to get that change into production cluster-wide.

**Comment by rtmclay** [comment] 2019-07-02 21:39
You don't have to set LMOD_ROOT.  It is already set by Lmod.  You have to logout and back in for it to be set.

```
% ml --config 2>&1 | grep MODULERCFILE
MODULERCFILE                       /opt/apps/lmod/etc/rc.lua
```

**Comment by rtmclay** [comment] 2019-07-02 22:00
Supporting  --sysconfdir=...  in Lmod is a problem. By default sysconfdir=${prefix}/etc  and that is a problem because that would normally be in your case prefix is /apps and sysconfig would be /apps/etc and not /apps/lmod/etc.  I see no way to safely use it if it defined by the user and not by default.  Comments?

**Comment by moskalenko** [comment] 2019-07-03 18:51
Even though LMOD_ROOT is declared in ${LMOD_DIR}/init/bash It doesn't appear to be set when module or ml is called as MODULERCFILE is still a relative path.

When I see 'sysconfdir' in the list of build time options and use it I'd expect MODULERCFILE to be set using that path instead of a relative path during the build. However, I don't see it used anywhere except in the 
config.status:S["sysconfdir"]="/apps/lmod/devetc"
If the original goal of sysconfdir is different can another configuration variable be set at a build time? After all Lmod sets some paths at build time and doesn't require them to be set from /etc/profile.d/modules.sh.

**Comment by rtmclay** [comment] 2019-07-03 19:18
The only way I see that MODULERCFILE could have a a relative path is in the following ways:

1. $LMOD_ROOT has no value
2. Lmod is configured with "--with-siteControlPrefix=yes"
3. $LMOD_ROOT has a relative path

What is the value of LMOD_ROOT in ${LMOD_DIR}/init/bash?
What is the value of $LMOD_ROOT in a bash shell?
What if you do the following?
```
   export LMOD_ROOT=/apps/lmod/etc/../etc; ml --config 2>&1 | grep MODULERCFILE
```

The problem with --sysconfdir= is not when it is set but when it is not.  LMOD_ROOT works for me so there must be something different at your site and I would like to see what it is.

**Comment by moskalenko** [comment] 2019-07-03 20:12
$LMOD_ROOT has no value in the environment even though it's set in ${LMOD_DIR}/init/bash to an absolute path '/apps/lmod'

The --with-siteControlPrefix was not used when configuring Lmod.

$ export LMOD_ROOT=/apps/lmod/etc/../etc; ml --config 2>&1 | grep MODULERCFILE
MODULERCFILE                       /apps/lmod/etc/../etc/etc/rc -> <empty>

**Comment by rtmclay** [comment] 2019-07-03 20:51
Thanks for your answers!  There is some issue in your setup that is causing ${LMOD_DIR}/init/bash not to be source.  I am wondering.  Is it possible that you are testing 8.1.9 but not completely installing it.  I do not know what your /etc/profile.d/module.sh has but mine has:

```
  if [ -f /opt/apps/lmod/lmod/init/$my_shell ]; then
     .    /opt/apps/lmod/lmod/init/$my_shell >/dev/null # Module Support
  else
     .    /opt/apps/lmod/lmod/init/sh        >/dev/null # Module Support
  fi
```
I suspect that you have something similar.  Is it possible that your startup scripts are source the "installed" version ${LMOD_DIR}/init/bash instead of Lmod 8.1.9?

LMOD_ROOT did not exist before Lmod 8.1.9 so using an older version would cause LMOD_ROOT not to be set.  If you are testing you might have to set LMOD_ROOT in the old version init/bash just to prove that it works.  Once Lmod 8.1.9 is completely installed it will be fine.

**Comment by rtmclay** [comment] 2019-07-12 19:38
O.K. to close this issue?

**Comment by moskalenko** [comment] 2019-07-12 19:58
Of course. We'll need to prepare and apply an /etc/profile.d/modules.sh update to set LMOD_ROOT, but that's on our side. Thank you Robert!

**Closed** 2019-07-12 20:23 UTC
