### ISSUE TITLE
restore fails after new modules installed

### ISSUE THREAD

**Issue by wpoely86** [TACC/Lmod#59] opened 2015-03-11 17:27 UTC
I saved a collection of modules and call restore at the start of my calculations. This worked beautiful until another version of a library that I loaded was installed. Lmod (correctly) decided that the other version should be the new default. This however give problems with the restore:
```
$ ml restore linmol-test1
Restoring modules to user's linmol-test1

Lmod Warning:  One or more modules in your  collection have changed: "GSL", "HDF5", "Libint". 
To rebuild the collection, load the modules you wish then do:
  $ module save 
If you no longer want this module collection do:
  rm ~/.lmod.d/

For more information execute 'module help' or see www.tacc.utexas.edu/tacc-projects/lmod/user-guide/loading-modules

Resetting modules to system default

The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
```
The problem seems to be that the 'default' status is also saved in the collection. I wonder why that is? 
I like it that a restore keeps on working even if newer versions of a module are installed.
The error handling also seems strange. Why restore the system default when the restore fails? Why not just keep what was loaded?

**Comment by rtmclay** [comment] 2015-03-11 19:00
The rule that Lmod uses is that you'd end up with the same modules loaded with a restore as if you'd done it by hand.  If one of the modules changes by say adding a new module, then you won't get the same modules loaded.   This means that Lmod can't use what the restore did. 

So the real question is what should Lmod do when the collection is "bad".  There are two cases.   The normal way for a site to load the initial set of modules is to do:

        $ module --initial_load restore default

This command will load the users' default collection if it exists.  If the default collection doesn't exist or is "bad" then it loads the system default.  If the LMOD_SYSTEM_DEFAULT_MODULES env. var exists and has a colon separated list of modules.  Then that gets loaded.  Otherwise nothing is loaded.

What I think that you are asking for is that:

      $ module restore foo

(as long as foo is not "default") then if the foo collection is bad then Lmod should error out and not change the state of the loaded modules.

Right?

**Comment by wpoely86** [comment] 2015-03-11 20:16
So if, I understand you correctly, it fails because I originally did `ml load HDF5` instead of `ml load HDF5/1.8.13-intel-2015a` and the default `HDF5` module has changed? This is not the behaviour I was expecting and I don't understand why it makes sense?

In my view, 2 things could happen with the save:
- No matter how it was loaded (including full version or not), `save` will store the currently load modules (including version) and `restore` will load them again, even if the default has changed.
- If I loaded the module through the default version `ml load HDF5`, `save` will store that and `restore` will always load the default module of that package (in that toolchain). If I load with the full version, that version will always be restored.

To my, the first points seems the most logical. The current behaviour of storing both the version and default state and giving an error if the default module has changed seems weird? Why would it matter to me if the default has changed since I did a `save`? I know what I want to load.

On the second point, yes, if Lmod cannot `restore`, it would expect it to leaves me in the current (working) state.

**Comment by boegel** [comment] 2015-03-11 20:24
I must say my gut feeling is that @wpoely86's 1st bullet point makes most sense, but I also agree with @rtmclay that there should be some way of specifying that a collection should load whatever the *current* default is if no version was specified when building the collection. However, that should be made explicit then, I think.

If you build your collection prior to using `save` with something like `ml --default HDF5`, then I don't think you'll be surprised if the `restore` also restores the default at that time.

But the default behaviour for a saved collection should be to restore whatever `ml` was printing at the time when `save` was run. If not, it kind of defeats the purpose of a collection, I think (at least, by default).

So, I'm a bit torn in between both options... Either way: things should be made *explicit*, e.g. `restore` could try and explain why it's restoring what it is restoring, e.g.:

```
$ ml restore foo
Restoring modules to user's linmol-test1, with (*): current default
* HDF5/1.8.12 (*)
* zlib/1.2.8
* GCC/4.8.3
* OpenMPI/1.8.2 (*)
```

**Comment by rtmclay** [comment] 2015-03-11 20:29
We do this all the time.  Namely the defaults can change and the collection will work even after the defaults change.  No the problem is with the loads.  I have seen EB generated modulefiles.  They contain loads.   If the loads change, then Lmod is going to have to mark the collection as "bad".   

As to your statements, Lmod makes the assumption that if you say "module load hdf5" you are requesting the default and you always get the default.   This is the case for collections as well.  If you want a specific version then you have to say "module load hdf5/1.8.12"  then you get that version.

It is the way that Lmod works with swaps and collections and everything else I know of.

If you want a collection to be of specific version then explicitly load full versions and make the collection.

**Comment by boegel** [comment] 2015-03-11 20:36
In general, the loads in existing (EB-generated) modules don't change, so marking a collection as 'bad' if they do makes sense.

I agree with you that not specifying a version implies that you're loading the default at that time. But that doesn't mean that people will expect this to also translate to a `restore`. I would think most people would expect to have `restore` reload all modules exactly like they were when they did the `save`.

Maybe also supporting a `ml restore --strict` would be an option?

I think you can argue for both options as a default, so just picking one (like you did) is fine, and the default can stay. But supporting both options in one way or another makes sense?

In any case, to debunk that expectation/assumption, which @wpoely86 also had, making the `restore` a bit more verbose as my example above showed, would help I think. That should make it clear what's going on, and people would be taken less off guard when their restore suddenly fails.

What do you think, @wpoely86?

**Comment by rtmclay** [comment] 2015-03-12 13:30
It might be possible to control what modulefiles are part of a collection at save time.   I don't have a good name for option but say:

      $ module save <collection>

works as Lmod has always worked.  Where as:

      $ module --exact save <collection>

would make Lmod convert any default module into the full name.  This would mean in the future restores of the collection would use the same modules at the time of saving even if the defaults changed.

As I said,  the name of the option is important and I am interested in a discussion on the name.

**Comment by boegel** [comment] 2015-03-12 13:34
`--strict`? `--robust`? `--current`?

It's weird to have the option flag that applies to `save` *before* the subcommand, btw. Just sayin'. ;-)

Are you interested in making the output of the `restore` more verbose too, to make it clear what's going on?

**Comment by wpoely86** [comment] 2015-03-12 13:41
`--exact` is quite good for me. Save exactly what is now loaded. Or `--fixed` / `--fixed-versions` to pin the current versions.

But to get back to the beginning, I don't understand why my restore failed? It should just have loaded the new defaults right? Why was it marked bad? Because it new modules tried to load a different version of the toolchain?

**Comment by rtmclay** [comment] 2015-03-12 18:56
I actually like --pin  or --pin_versions  (or to keep @boegel happy) --pin-versions as the option name.  

Q1:  All options are handled this way:  module [options] <command>  


Q2: Why did the restore fail:   For reasons that are hard to explain, all load commands in a modulefile are no-ops when a restore happens.  To avoid problems, Lmod remembers the text in the Load functions in modulefiles.  So suppose you have a default HDF5 module (1.8.12) in your collection at the time of the save.  Today you restore and the default HDF5 module is 1.8.13.  If the 1.8.13 modulefile contains load statement that are different then the 1.8.12 module file, then Lmod detects the change and says the collection is out of date and therefore "bad".

Q3: make the restore more verbose?  No I don't think so.  However, I am thinking about some message that will be reported if a collection is bad.  Maybe something like:

       Collections remember whether a module is default or not.  If module defaults change then
       so will the modules in your collection.  If you want to save (or restore) the same version at 
       the time of the save then do:

              $ module --pin save  <collection>

      or
              $ module --pin restore <collection>

@wpoely86, @boegel comments?

**Comment by boegel** [comment] 2015-03-12 18:59
Sounds good, `--pin-versions` would make sense, `--pin` is a bit generic/unspecified, I think.

I'm not sure what you don't like about making the restore a bit more verbose, but fine. :-)

**Comment by rtmclay** [comment] 2015-03-12 19:13
Because it is standard for many sites to load the default modules in /etc/profile.d by doing:

    module --initial_load restore

That command should be should be silent unless the user has a default collection which is bad.

**Comment by boegel** [comment] 2015-03-12 19:27
So, then don't be verbose when `--initial_load` is used (by default)?

**Comment by rtmclay** [comment] 2015-03-12 19:40
:)

**Comment by wpoely86** [comment] 2015-03-13 09:33
`--pin-versions` is fine by me.

Okay, I understand why it fails now. It would suggest to have a config option to make `--pin-versions` the default. With EB generated modules, the default load will only work as long as the default doesn't change. This will bite users in the ass as something will 'suddenly' stop working. 

For my personal use case, I will always want to pin versions too. Loading the default is never what I want to do.

**Comment by rtmclay** [comment] 2015-03-18 03:47
I have updated Lmod to support --pin-versions.  Lmod can be configured to always run this way.  Or the env. variable LMOD_PIN_VERSIONS is set to "yes".  This is pushed to HEAD and it is labelled as version 5.9.1.1

**Comment by wpoely86** [comment] 2015-03-18 08:18
Great!
As soon as @boegel rolls it out, I will give it a spin.

**Comment by boegel** [comment] 2015-03-18 09:28
Installed, test away @wpoely86!

**Comment by rtmclay** [comment] 2015-03-24 16:11
Have you guys tested this out.  Can I close this issue?

**Comment by wpoely86** [comment] 2015-03-24 16:15
Almost, other problems turned up (related to the UGent-HPC setup, not Lmod). They're almost fixed.

**Comment by wpoely86** [comment] 2015-03-25 08:23
Finally tested it and it works great. Thanks @rtmclay!

**Closed** 2015-03-25 08:23 UTC

**Comment by wpoely86** [comment] 2015-03-25 10:44
A follow up issue: sticky modules. Should a restore touch sticky modules? In UGent-HPC the cluster you're working on (and thus the module path) depends on a module. Once you've picked a cluster, that module should never change unless  you do it explicit (with a swap). If I currently make a collection with cluster module A and want to use it on cluster module B, it will not work as it will always load cluster module A too. 

Maybe it should be an option to let restore skip sticky modules? @boegel your take on this?

**Comment by boegel** [comment] 2015-03-25 10:46
@wpoely86: you should unload the `cluster` module before using `ml save`?

**Comment by wpoely86** [comment] 2015-03-25 10:47
@boegel that would probably work but it doesn't exactly fall under the category 'user-friendly'...

**Comment by boegel** [comment] 2015-03-25 10:55
Actually, I'm not sure if it'll work, since unloading `cluster` will trigger a change in `$MODULEPATH`, making Lmod put all modules to inactive.

**Comment by rtmclay** [comment] 2015-03-25 15:41
Collections remember a list of modules and restore them.  That's all.   If one module is different then it needs to be a different collection.

**Comment by wpoely86** [comment] 2015-03-25 15:44
That means I would need a collection per cluster module even do the contents of the collection is exactly the same (with the exception of the sticky module). 
Shouldn't stick mean that the modules stays there unless you explicitly let it unload (using `--force`)?

**Comment by rtmclay** [comment] 2015-03-25 17:03
Yes.

**Comment by rtmclay** [comment] 2015-03-25 17:04
The rules of collections are that you get exactly the same set of modules
every time.

**Comment by rtmclay** [comment] 2015-03-25 18:12
That means that the restore is a forced purged followed by a load of the list.  It is the only way to guarantee that you get the same modules when you do a restore.
