### ISSUE TITLE
module avail always shows all extensions, also those for modules that are not available

### ISSUE THREAD

**Issue by klust** [TACC/Lmod#560] opened 2022-02-02 11:56 UTC
I noticed that module avail always shows all extensions for all installed modules, not just for the available modules. Is this a deliberate design choice or should this be considered a bug? 

Personally I would expect that if a module is not shown by module avail, its extensions should also not be shown.

I've tested this in the 8.6.8 version of LMOD also (not just on the stone age version that Cray provides) and the "feature" is still present.

**Comment by rtmclay** [comment] 2022-02-09 22:13
Thanks very much for the bug report!    I was able to reproduce your issue and fix it for me.  Please test Lmod 8.6.12 to see if it fixes this issue for you.  Thanks!

**Comment by klust** [comment] 2022-02-10 14:07
It seems fixed for me too but I'll do some further testing later. The main system I'm working on is down for major maintenance this week and next week so I had to quickly set something up on a different system I have access to.

**Comment by rtmclay** [comment] 2022-02-17 23:46
@wpoely86 is correct. The latest on master will now not show extensions from hidden modules. (unless doing 
`module --show_hidden avail`)  Nice catch!

**Comment by rtmclay** [comment] 2022-02-19 14:29
@wpoely86: You are correct.  Lmod 8.6.12 would show extensions from hidden modules.  I have updated my copy of Lmod to fix this issue.  It will be part of the next release of Lmod.

**Comment by rtmclay** [comment] 2022-02-26 00:30
Please test Lmod 8.6.13 to see that extensions in hidden modulefiles are not displayed when doing "module avail"

**Comment by wpoely86** [comment] 2022-02-28 09:57
I've tested this with the `isVisible` hook and it works as intended.

Only thing I noticed (and not sure if we want this): hidden modules get a `H`, hidden extensions not.

**Comment by rtmclay** [comment] 2022-02-28 21:28
Since extensions are by shortName and not full version it makes to show what is hidden or not.  Also extensions like numpy might be both hidden and not. Lets leave it as is.  I will add it to be discussed in March 1, 2022 Lmod Zoom Mtg.

**Closed** 2022-03-08 18:02 UTC
