### ISSUE TITLE
`ml refresh` random error

### ISSUE THREAD

**Issue by kcgthb** [TACC/Lmod#609] opened 2022-11-01 18:49 UTC
`ml refresh` sometimes fails with the following error:
```
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/system/freetype/2.8.1.lua: [string "-- -*- lua -*-..."]:37: attempt to concatenate field 'name' (a boolean value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
```
whereas the initial `module load` obviously worked (since the module is... loaded).

This looks like a recent regression, as I don't remember having any issue with `ml refresh` before. This is also something that doesn't happen systematically, but seems to be more frequent when modules with dependencies are loaded. 

I haven't been able to isolate the root cause of the error, as sometimes the same module loaded on its own can be successfully refreshed, but sometimes, when loaded as a dependency of another module, the error above happens.

For instance, the `freetype` module on its own is ok:
```
$ ml freetype/2.8.1
$ ml

Currently Loaded Modules:
  1) devel (S)   2) math (S)   3) system   4) zlib/1.2.11   5) libpng/1.2.57   6) freetype/2.8.1

  Where:
   S:  Module is Sticky, requires --force to unload or purge
$ ml refresh
$
```

But when loaded as a dependency of another module (like `octave` here), `ml refresh` fails:
```
$ ml octave
$ ml

Currently Loaded Modules:
  1) devel       (S)   6) hdf5/1.10.0p1       11) fontconfig/2.12.4   16) mesa/17.1.6    21) fltk/1.3.4      26) openblas/0.2.19  31) viz                           36) harfbuzz/1.4.8       41) libwebp/0.6.1          46) octave/4.2.1
  2) math        (S)   7) openmpi/2.0.2  (m)  12) libxml2/2.9.4       17) sqlite/3.18.0  22) java/1.8.0_131  27) arpack/3.5.0     32) libffi/3.2.1                  37) pango/1.40.10        42) libgd/2.2.5
  3) system            8) fftw/3.3.6     (m)  13) llvm/4.0.0          18) icu/59.1       23) readline/7.0    28) glpk/4.63        33) glib/2.52.3                   38) libjpeg-turbo/1.5.1  43) gnuplot/5.2.0
  4) zlib/1.2.11       9) libpng/1.2.57       14) libxkbcommon/0.9.1  19) ruby/2.4.1     24) libressl/2.5.3  29) qhull/2015.2     34) gobject-introspection/1.52.1  39) libtiff/4.0.8        44) xz/5.2.3
  5) szip/2.1.1       10) freetype/2.8.1      15) x11/7.7             20) qt/5.9.1       25) curl/7.54.0     30) qrupdate/1.1.2   35) cairo/1.14.10                 40) giflib/5.1.4         45) graphicsmagick/1.3.26

  Where:
   S:  Module is Sticky, requires --force to unload or purge
   m:  MPI support
$ ml refresh
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/system/freetype/2.8.1.lua: [string "-- -*- lua -*-..."]:37: attempt to concatenate field 'name' (a boolean value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
```

All our modules are built on the same template, and the section that seems to generate the error is this:
```
local pkg = {}
pkg.name = myModuleName()
[...]
whatis("Name:        " .. pkg.name)
[...]
```
The line that is referenced in the error is the `whatis("Name:        " .. pkg.name)` line.

Here's the mini config:
```
$ module --miniConfig

Modules based on Lua: Version 8.7.13  2022-09-14 12:56 -05:00
    by Robert McLay mclay@tacc.utexas.edu

Changes from Default Configuration
----------------------------------

Name                         Where Set  Default                                        Value
----                         ---------  -------                                        -----
LFS_VERSION                  D          1.6.3                                          1.8.0
LMOD_ADMIN_FILE              E          /share/software/user/open/lmod/etc/admin.list  /share/software/modules/admin.list
LMOD_AVAIL_STYLE             E          <system>                                       categories
LMOD_FAST_TCL_INTERP         C          yes                                            no
LMOD_MODULERCFILE            E          /share/software/user/open/lmod/etc/rc          /share/software/modules/.modulerc.lua
LMOD_PACKAGE_PATH            D          nil                                            /share/software/modules/
LMOD_PAGER                   C          less                                           /bin/less
LMOD_RC                      E                                                         /share/software/modules/lmodrc.lua
LMOD_REDIRECT                E          no                                             yes
LMOD_SITE_NAME               C          false                                          sherlock
LMOD_SYSHOST                 E          false                                          sherlock
LMOD_SYSTEM_DEFAULT_MODULES  E          __unknown__                                    devel,math
LMOD_TCLSH                   C          tclsh                                          /bin/tclsh
MODULEPATH_ROOT              E                                                         /share/software/modules
PATH_TO_LUA                  C          lua                                            /bin/lua


Where Set -> D: default, E: environment, C: configuration
             lmod_cfg: lmod_config.lua SitePkg: SitePackage StdPkg: StandardPackage
             Other: Set somewhere outside of normal locations
```

Any hint on how to debug this further?

Thanks!

**Comment by rtmclay** [comment] 2022-11-02 15:39
the command "module refresh" only "runs" the set_alias() and set_shell_function().  In particular, the function setenv() is a no-op.  My guess is that in some cases, your modulefile depends on an env. var. that might not be set and you get that error.

Hopefully, this helps
________________________________
From: Kilian Cavalotti ***@***.***>
Sent: Tuesday, November 1, 2022 1:49 PM
To: TACC/Lmod ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TACC/Lmod] `ml refresh` random error (Issue #609)


ml refresh sometimes fails with the following error:

Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/system/freetype/2.8.1.lua: [string "-- -*- lua -*-..."]:37: attempt to concatenate field 'name' (a boolean value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------


whereas the initial module load obviously worked (since the module is... loaded).

This looks like a recent regression, as I don't remember having any issue with ml refresh before. This is also something that doesn't happen systematically, but seems to be more frequent when modules with dependencies are loaded.

I haven't been able to isolate the root cause of the error, as sometimes the same module loaded on its own can be successfully refreshed, but sometimes, when loaded as a dependency of another module, the error above happens.

For instance, the freetype module on its own is ok:

$ ml freetype/2.8.1
$ ml

Currently Loaded Modules:
  1) devel (S)   2) math (S)   3) system   4) zlib/1.2.11   5) libpng/1.2.57   6) freetype/2.8.1

  Where:
   S:  Module is Sticky, requires --force to unload or purge
$ ml refresh
$


But when loaded as a dependency of another module (like octave here), ml refresh fails:

$ ml octave
$ ml

Currently Loaded Modules:
  1) devel       (S)   6) hdf5/1.10.0p1       11) fontconfig/2.12.4   16) mesa/17.1.6    21) fltk/1.3.4      26) openblas/0.2.19  31) viz                           36) harfbuzz/1.4.8       41) libwebp/0.6.1          46) octave/4.2.1
  2) math        (S)   7) openmpi/2.0.2  (m)  12) libxml2/2.9.4       17) sqlite/3.18.0  22) java/1.8.0_131  27) arpack/3.5.0     32) libffi/3.2.1                  37) pango/1.40.10        42) libgd/2.2.5
  3) system            8) fftw/3.3.6     (m)  13) llvm/4.0.0          18) icu/59.1       23) readline/7.0    28) glpk/4.63        33) glib/2.52.3                   38) libjpeg-turbo/1.5.1  43) gnuplot/5.2.0
  4) zlib/1.2.11       9) libpng/1.2.57       14) libxkbcommon/0.9.1  19) ruby/2.4.1     24) libressl/2.5.3  29) qhull/2015.2     34) gobject-introspection/1.52.1  39) libtiff/4.0.8        44) xz/5.2.3
  5) szip/2.1.1       10) freetype/2.8.1      15) x11/7.7             20) qt/5.9.1       25) curl/7.54.0     30) qrupdate/1.1.2   35) cairo/1.14.10                 40) giflib/5.1.4         45) graphicsmagick/1.3.26

  Where:
   S:  Module is Sticky, requires --force to unload or purge
   m:  MPI support
$ ml refresh
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/system/freetype/2.8.1.lua: [string "-- -*- lua -*-..."]:37: attempt to concatenate field 'name' (a boolean value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------


All our modules are built on the same template, and the section that seems to generate the error is this:

local pkg = {}
pkg.name = myModuleName()
[...]
whatis("Name:        " .. pkg.name)
[...]


The line that is referenced in the error is the whatis("Name: " .. pkg.name) line.

Here's the mini config:

$ module --miniConfig

Modules based on Lua: Version 8.7.13  2022-09-14 12:56 -05:00
    by Robert McLay ***@***.***

Changes from Default Configuration
----------------------------------

Name                         Where Set  Default                                        Value
----                         ---------  -------                                        -----
LFS_VERSION                  D          1.6.3                                          1.8.0
LMOD_ADMIN_FILE              E          /share/software/user/open/lmod/etc/admin.list  /share/software/modules/admin.list
LMOD_AVAIL_STYLE             E          <system>                                       categories
LMOD_FAST_TCL_INTERP         C          yes                                            no
LMOD_MODULERCFILE            E          /share/software/user/open/lmod/etc/rc          /share/software/modules/.modulerc.lua
LMOD_PACKAGE_PATH            D          nil                                            /share/software/modules/
LMOD_PAGER                   C          less                                           /bin/less
LMOD_RC                      E                                                         /share/software/modules/lmodrc.lua
LMOD_REDIRECT                E          no                                             yes
LMOD_SITE_NAME               C          false                                          sherlock
LMOD_SYSHOST                 E          false                                          sherlock
LMOD_SYSTEM_DEFAULT_MODULES  E          __unknown__                                    devel,math
LMOD_TCLSH                   C          tclsh                                          /bin/tclsh
MODULEPATH_ROOT              E                                                         /share/software/modules
PATH_TO_LUA                  C          lua                                            /bin/lua


Where Set -> D: default, E: environment, C: configuration
             lmod_cfg: lmod_config.lua SitePkg: SitePackage StdPkg: StandardPackage
             Other: Set somewhere outside of normal locations


Any hint on how to debug this further?

Thanks!

**Comment by kcgthb** [comment] 2022-11-02 16:39
Hi @rtmclay!

> the command "module refresh" only "runs" the set_alias() and set_shell_function().  In particular, the function setenv() is a no-op.  

All right, that's very good to know, thanks!

I actually found a reproducer, and I think it's related to "extended defaults". Depending on how the module is loaded, a `ml refresh` may work (if the full version number is used) or not (if a "shortcut" is used). 

Here's a minimal example, with the following test module (`test/10.01.lua`)
```
local pkg = {}
pkg.name = myModuleName()
whatis("Name: " .. pkg.name)
set_shell_function("foo", "echo ok")
```

When loading the module as either `test` or `test/10.01`, `ml refresh` works:
```
$ ml test
$ ml

Currently Loaded Modules:
  1) test/10.01
$ ml refresh
$
$ ml -test
$ ml test/10.01
$ ml refresh
$
```

But if it's loaded as `test/10`, then `ml refresh` fails:
```
$ ml -test
$ ml test/10
$ ml refresh
Lmod has detected the following error:  Unable to load module because of error when evaluating modulefile:
     /share/software/modules/staging/test/10.01.lua: [string "local pkg = {}..."]:3: attempt to concatenate field 'name' (a boolean value)
     Please check the modulefile and especially if there is a line number specified in the above message
While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
$
```

Hopefully that will help track down the problem.

Thanks!

**Comment by rtmclay** [comment] 2022-11-04 19:55
It turns out that this was fixed by Issue #607. I updated my tests with your test case to show that it works for me.  Please test Lmod 8.7.14 to see if it works for you.  Thanks for the bug report!

**Comment by kcgthb** [comment] 2022-11-04 20:54
Ah great, thank you!
Confirmed that 8.7.14 fixes the issue for me.

**Comment by rtmclay** [comment] 2022-11-05 23:24
Thanks for testing!  Closing this issue

**Closed by rtmclay** 2022-11-05 23:24 UTC
