### ISSUE TITLE
conflicting module warnings not printed when multiple modules loaded

### ISSUE THREAD

**Issue by bmcgough** [TACC/Lmod#463] opened 2020-09-02 19:12 UTC
We have a case where 'module load a' followed by 'module load b' produces warnings about 28 dependent modules being replaced.

When we do 'module load a b' it just returns silently, giving no warning that incompatibilities may exist.

Lmod 8.3.10 on Ubuntu 18.04.

Frighteningly, in this case, the end application (module a) ran without error but produced wildly different results with the same inputs.

**Comment by rtmclay** [comment] 2020-09-02 19:36
Please put together a test case that shows this problem.  Also please show that this test case fails with the latest version of Lmod.   Thanks, Robert.

**Comment by rtmclay** [comment] 2020-09-22 21:48
If you are still interested in looking at this issue, you might consider using the -T trace option to see what loads and unloads Lmod is doing.

**Comment by rtmclay** [comment] 2020-10-06 02:21
I am closing this issue because there is no information on how to reproduce this.  Please feel free to reopen this if you can provide a test case.

**Closed by rtmclay** 2020-10-06 02:21 UTC
