### ISSUE TITLE
Infinite load loop when dependencies loaded through module load

### ISSUE THREAD

**Issue by xdelaruelle** [TACC/Lmod#655] opened 2023-06-03 19:14 UTC
Hello Robert,

**Describe the bug**
There is [an issue reported on Spack](https://github.com/spack/spack/issues/36764) where someone installs `py-jupyter` with generation of `tcl` modulefiles. When loading `py-jupyter` module, an infinite load loop error is obtained.

```console
$ module load py-jupyter
Lmod has detected the following error:  Infinite Load Loop detected for module: "ncurses/6.4-gcc-13.1.1-mwwshua" file:
"/home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/ncurses/6.4-gcc-13.1.1-mwwshua"
While processing the following module(s):
    Module fullname                         Module Filename
    ---------------                         ---------------
    ncurses/6.4-gcc-13.1.1-mwwshua          /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/ncurses/6.4-gcc-13.1.1-mwwshua
    readline/8.2-gcc-13.1.1-2gng7tj         /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/readline/8.2-gcc-13.1.1-2gng7tj
    gdbm/1.23-gcc-13.1.1-ws52ulr            /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/gdbm/1.23-gcc-13.1.1-ws52ulr
    python/3.10.10-gcc-13.1.1-m6so4xi       /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/python/3.10.10-gcc-13.1.1-m6so4xi
    py-greenlet/2.0.2-gcc-13.1.1-wr2hlvf    /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/py-greenlet/2.0.2-gcc-13.1.1-wr2hlvf
    py-gevent/1.5.0-gcc-13.1.1-wqurm3w      /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/py-gevent/1.5.0-gcc-13.1.1-wqurm3w
    py-pyzmq/25.0.2-gcc-13.1.1-fboajce      /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/py-pyzmq/25.0.2-gcc-13.1.1-fboajce
    py-ipykernel/6.22.0-gcc-13.1.1-nrs3fjt  /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/py-ipykernel/6.22.0-gcc-13.1.1-nrs3fjt
    py-ipywidgets/8.0.2-gcc-13.1.1-nl6ddfo  /home/user/devel/spack/share/spack/modules/linux-fedora38-skylake/py-ipywidgets/8.0.2-gcc-13.1.1-nl6ddfo
```

In the `tcl` modulefiles generated by Spack, dependencies are loaded with `module load` commands. From what I observe with `--trace` option, a storm of unload/load happens when loading dependencies. 

The modulefiles do not seem to define a dependency loop.

Changing the `module load` statements by `depends-on`, no infinite load loop is detected and the command succeeds.

Infinite load loop is also observed with `lua` modulefiles when `load()` command is used to load dependencies.

I would like to know if some correction could be made to be able to load dependencies with `module load`.

**To Reproduce**
* Unzip `modulefiles.tar.gz` archive attached to this issue
* module use ./modulefiles
* module load py-jupyter

**Expected behavior**
No infinite load loop when loading dependencies with `module load`.

**Desktop**
 - OS: Linux
 - Linux distribution: Fedora 38
 - Lmod Version: 8.7.25

```console
$ module --miniConfig

Modules based on Lua: Version 8.7.25  2023-05-18 17:01 -05:00
    by Robert McLay mclay@tacc.utexas.edu

Changes from Default Configuration
----------------------------------

Name                         Where Set  Default                                         Value
----                         ---------  -------                                         -----
LFS_VERSION                  D          1.6.3                                           1.8.0
LMOD_HAVE_LUA_TERM           C          no                                              yes
LMOD_PACKAGE_PATH            D          nil                                             <empty>
LMOD_PAGER                   C          less                                            /usr/bin/less
LMOD_SITEPACKAGE_LOCATION    Other      /usr/local/lmod/8.7.25/libexec/SitePackage.lua  <srctree>
LMOD_SYSTEM_DEFAULT_MODULES  D          __unknown__                                     <empty>
LMOD_TCLSH                   C          tclsh                                           /usr/bin/tclsh
MODULEPATH_ROOT              C                                                          NONE/modulefiles
PATH_TO_LUA                  C          lua                                             /usr/bin/lua


Where Set -> D: default, E: environment, C: configuration
             lmod_cfg: lmod_config.lua SitePkg: SitePackage StdPkg: StandardPackage
             Other: Set somewhere outside of normal locations
```
[modulefiles.tar.gz](https://github.com/TACC/Lmod/files/11643457/modulefiles.tar.gz)

Best regards,
Xavier

**Comment by boegel** [comment] 2023-06-06 16:12
I can reproduce the problem with the provided testcase easily (using Lmod 8.7.6 on macOS, installed with `brew`)

We briefly discussed this during today's Lmod monthly meeting, but no clear cause yet.

It seems like there are no `$MODULEPATH` changes are being made (@rtmclay mentioned that as a likely factor), unless I'm overlooking something.

Attaching the output of `module --trace load py-jupyter`, which failed after over 10994 loads+unloads, for closer inspection...

[lmod_trace_load_issue-655.txt](https://github.com/TACC/Lmod/files/11666835/lmod_trace_load_issue-655.txt)

**Comment by rtmclay** [comment] 2023-06-07 20:37
This is **NOT** an Lmod bug.  Lmod is doing exact what is suppose to do.  When a user or a modulefile requests a load() it does a load().  It doesn't check to see if the modulefile is already loaded, Lmod unloads the old one and then reloads it.

The issue is with loading the py-jupyter modulefile, it depends on many module like py-ipykernal, py-comm, ....
Several of these modules depend on bzip2, ncurses, zlib, xz, etc.  This is what is causing the load storm.

Using depends_on() does check to see if the modulefile is already loaded.  The function load() doesn't.  I would recommend that these modulefiles be re-generated to wrap the module load with a is-loaded test.  For example:
```
module load bzip2/1.0.8-gcc-13.1.1-rfmtfef
```
to
``` 
if { ! [  is-loaded bzip2/1.0.8-gcc-13.1.1-rfmtfef ] } {
   module load bzip2/1.0.8-gcc-13.1.1-rfmtfef
}
```

In checking TCL modulefile generated by Easybuild.  I see that they do a similar wrapping each module load with an is-loaded test.

**Comment by xdelaruelle** [comment] 2023-06-08 04:01
Thanks Robert for your answer.

Wrapping the `module load` command in an `is-loaded` test is problematic. If module is already loaded, requirement definition is skipped. Then if this requirement is later unloaded, no error or auto-unload of the dependent module will be triggered.

What is clear for me now is that `depends-on` should be preferred over `module load` to define requirements for Lmod.

`depends-on` modulefile command is only known since Modules v5.1. Even though this mechanism is there since v4.2 through either `prereq` or `module load` modulefile commands.

I will propose a template adaptation for Spack to make both Lmod and Modules working correctly:

```tcl
if {[info exists ::env(LMOD_VERSION_MAJOR)]} {
    depends-on bzip2/1.0.8-gcc-13.1.1-rfmtfef
} else {
    module load bzip2/1.0.8-gcc-13.1.1-rfmtfef
}
```

At some point I will also investigate the modulefile generation mechanism of EasyBuild to see if I can help make it better support Environment Modules.

**Comment by boegel** [comment] 2023-06-08 15:11
I understand that it's difficult to recognize an actual infinite loop, but then at the very least the error could be more accurate.
Here's a concrete suggestion:

```
Lmod has detected the following error: Infinite Load Loop or Load Storm detected while loading module
"py-ipywidgets/8.0.2-gcc-13.1.1-nl6ddfo ": module "ncurses/6.4-gcc-13.1.1-mwwshua" got loaded 500 times!
See https://lmod.readthedocs.io/en/latest/999_load_storm.html for more information.
```

**Comment by xdelaruelle** [comment] 2023-06-08 18:33
> @xdelaruelle Your proposed solution to use depends-on (in TCL) works for me and is better in lots of ways over wrapping loads with an is-loaded test. However, I don't understand your comment about using is-loaded. Why is approach problematical?

It seems that my comment only applies to Modules, as it seems that Lmod re-read loaded modulefiles when unloading a module.

On Modules, module requirement are caught at load time. So if a requirement command like `module load` or `depends-on` is skipped (due to the *if* wrapping), the loaded module will not express the requirement information which is then used at unload time.

**Comment by rtmclay** [comment] 2023-06-12 21:17
I'm closing this issue.  If there is any question about the new error message, please feel free to reopen this issue

**Closed by rtmclay** 2023-06-12 21:17 UTC
